#!/usr/bin/env python3
"""Idempotent ROCm/HIP compatibility patcher for microduck_rl dependencies.

microduck_rl trains through mjlab -> mujoco-warp -> NVIDIA Warp, a CUDA-only
stack. AMD publishes a ROCm/HIP port of Warp (AMD-Ecosystem/warp, branch
amd-integration). With that Warp wheel plus a HIP-major-matched PyTorch, the
only remaining gaps are four small incompatibilities inside the installed
dependency packages (mjlab, mujoco-warp) and one missing public alias in the
Warp fork. This script fixes all of them in place, in the active virtualenv's
site-packages. It is safe to run repeatedly: every edit is guarded and skipped
if already applied.

Fixes applied:
  1. warp.context alias    - the ROCm fork moved `warp.context` to
                             `warp._src.context`; mjlab imports `wp.context.*`.
  2. solver graph capture  - mujoco-warp's solver uses `wp.capture_while`
                             (conditional CUDA-graph nodes) which the ROCm Warp
                             backend does not support. mjlab is told to disable
                             conditional graphs so the solver takes its native
                             Python-loop fallback branch.
  3. render textures        - mujoco-warp's create_render_context builds
                             wp.Texture2D objects (hipArray) even for
                             raycast-only contexts; hipArray textures are not
                             supported by the ROCm Warp backend, so the texture
                             loop is guarded by the existing use_textures flag.

Run: python rocm/patch_rocm.py [--check]
  --check : report status only, make no changes (exit 1 if any patch missing).
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
import sysconfig
from pathlib import Path


def _site_packages() -> Path:
    p = sysconfig.get_paths().get("purelib")
    return Path(p) if p else Path(sys.prefix) / "lib"


def _find(pkg_file: str) -> Path | None:
    """Locate a module file by dotted import path without importing it."""
    try:
        spec = importlib.util.find_spec(pkg_file)
    except (ImportError, ValueError, ModuleNotFoundError):
        return None
    if spec and spec.origin and spec.origin != "built-in":
        return Path(spec.origin)
    return None


class Patch:
    def __init__(self, name: str):
        self.name = name

    def status(self) -> str:
        raise NotImplementedError

    def apply(self) -> str:
        raise NotImplementedError


class ContextShim(Patch):
    """Install a .pth + shim module that aliases warp.context -> warp._src.context."""

    def __init__(self):
        super().__init__("warp.context alias")
        self.sp = _site_packages()
        self.pth = self.sp / "warp_rocm_compat.pth"
        self.mod = self.sp / "warp_rocm_compat_shim.py"

    def status(self) -> str:
        return "present" if (self.pth.exists() and self.mod.exists()) else "missing"

    def apply(self) -> str:
        if self.status() == "present":
            return "skip (already present)"
        self.mod.write_text(
            "# Auto-generated by microduck_rl rocm/patch_rocm.py\n"
            "# Alias warp.context (public in warp<=1.12) to warp._src.context,\n"
            "# where the AMD ROCm Warp fork relocated it. mjlab/mujoco-warp use\n"
            "# wp.context.* and wp.context.Device.\n"
            "import sys, importlib\n"
            "def _install():\n"
            "    try:\n"
            "        import warp\n"
            "    except Exception:\n"
            "        return\n"
            "    if hasattr(warp, 'context'):\n"
            "        return\n"
            "    try:\n"
            "        ctx = importlib.import_module('warp._src.context')\n"
            "    except Exception:\n"
            "        return\n"
            "    warp.context = ctx\n"
            "    sys.modules['warp.context'] = ctx\n"
            "try:\n"
            "    import warp  # noqa: F401\n"
            "    _install()\n"
            "except Exception:\n"
            "    import builtins\n"
            "    _orig = builtins.__import__\n"
            "    def _hook(name, *a, **k):\n"
            "        m = _orig(name, *a, **k)\n"
            "        if name == 'warp' or name.startswith('warp.'):\n"
            "            try:\n"
            "                w = sys.modules.get('warp')\n"
            "                if w is not None and not hasattr(w, 'context'):\n"
            "                    c = importlib.import_module('warp._src.context')\n"
            "                    w.context = c\n"
            "                    sys.modules['warp.context'] = c\n"
            "            except Exception:\n"
            "                pass\n"
            "        return m\n"
            "    builtins.__import__ = _hook\n"
        )
        self.pth.write_text("import warp_rocm_compat_shim\n")
        return "installed .pth + shim"


class GraphConditionalOff(Patch):
    """Force mjlab to disable mujoco-warp conditional CUDA graphs (unsupported on ROCm)."""

    MARK = "ROCm/HIP: conditional CUDA-graph nodes unsupported"

    def __init__(self):
        super().__init__("solver graph_conditional=False (mjlab)")
        self.path = _find("mjlab.sim.sim")

    def status(self) -> str:
        if not self.path or not self.path.exists():
            return "target-missing"
        return "present" if self.MARK in self.path.read_text() else "missing"

    def apply(self) -> str:
        st = self.status()
        if st != "missing":
            return f"skip ({st})"
        assert self.path is not None  # status() would have returned target-missing
        s = self.path.read_text()
        anchor = "      self._wp_model.opt.ls_parallel = cfg.ls_parallel\n"
        if anchor not in s:
            # fall back to any indentation of the same assignment
            import re
            m = re.search(r"^(\s*)self\._wp_model\.opt\.ls_parallel = cfg\.ls_parallel\n", s, re.M)
            if not m:
                return "FAILED (anchor not found)"
            indent = m.group(1)
            anchor = m.group(0)
        else:
            indent = "      "
        inject = (
            f"{indent}# {self.MARK}; force the mujoco-warp solver onto its native\n"
            f"{indent}# Python-loop fallback branch instead of wp.capture_while.\n"
            f"{indent}self._wp_model.opt.graph_conditional = False\n"
        )
        s = s.replace(anchor, anchor + inject, 1)
        self.path.write_text(s)
        return f"patched {self.path}"


class TextureGuard(Patch):
    """Guard mujoco-warp's unconditional texture creation with its use_textures flag."""

    MARK = "ROCm/HIP: wp.Texture2D (hipArray) unsupported"

    def __init__(self):
        super().__init__("render texture guard (mujoco-warp)")
        self.path = _find("mujoco_warp._src.io")

    def status(self) -> str:
        if not self.path or not self.path.exists():
            return "target-missing"
        s = self.path.read_text()
        if self.MARK in s:
            return "present"
        # Already guarded by an equivalent edit (e.g. a newer mujoco-warp that
        # honors use_textures, or a prior run): treat as present, do not re-patch.
        if "if use_textures:\n    for i in range(mjm.ntex):" in s:
            return "present"
        return "missing"

    def apply(self) -> str:
        st = self.status()
        if st != "missing":
            return f"skip ({st})"
        assert self.path is not None  # status() would have returned target-missing
        s = self.path.read_text()
        old = (
            "  textures_registry = []\n"
            "  for i in range(mjm.ntex):\n"
            "    textures_registry.append(render_util.create_warp_texture(mjm, i))\n"
            "  textures = wp.array(textures_registry, dtype=wp.Texture2D)"
        )
        if old not in s:
            return "FAILED (anchor not found; mujoco-warp version may differ)"
        new = (
            "  textures_registry = []\n"
            f"  # {self.MARK} by the AMD ROCm Warp backend (CUDA error 801).\n"
            "  # Only build textures when the caller needs camera rendering;\n"
            "  # raycast-only contexts pass use_textures=False.\n"
            "  if use_textures:\n"
            "    for i in range(mjm.ntex):\n"
            "      textures_registry.append(render_util.create_warp_texture(mjm, i))\n"
            "  textures = wp.array(textures_registry, dtype=wp.Texture2D) if textures_registry else None"
        )
        s = s.replace(old, new, 1)
        self.path.write_text(s)
        return f"patched {self.path}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report status only, make no changes")
    args = ap.parse_args()

    patches = [ContextShim(), GraphConditionalOff(), TextureGuard()]

    print(f"site-packages: {_site_packages()}")
    if args.check:
        missing = 0
        for p in patches:
            st = p.status()
            print(f"  [{st:>14}] {p.name}")
            if st in ("missing", "target-missing"):
                missing += 1
        if missing:
            print(f"{missing} patch(es) not applied.")
            return 1
        print("All ROCm patches present.")
        return 0

    failed = 0
    for p in patches:
        res = p.apply()
        print(f"  {p.name}: {res}")
        if res.startswith("FAILED"):
            failed += 1
    if failed:
        print(f"{failed} patch(es) FAILED.")
        return 1
    print("All ROCm patches applied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
